root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main cmd/api/main.go"
bin = "./tmp/main"
full_bin = "./tmp/main -config config/config.yaml"
include_ext = ["go", "yaml"]
exclude_dir = ["tmp", "vendor", "test"]
include_dir = []
exclude_file = []
delay = 1000
stop_on_error = true
send_interrupt = false
kill_delay = 500

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true 