app:
  name: gohex
  environment: development
  version: 1.0.0

http:
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

database:
  driver: mysql
  host: localhost
  port: 3306
  database: gohex
  username: root
  password: secret
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 1h

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

jwt:
  secret_key: your-secret-key
  token_duration: 24h

log:
  level: debug
  format: json
  output_path: stdout

auth:
  jwt:
    secret_key: your-secret-key
    access_ttl: 15m
    refresh_ttl: 7d
    issuer: gohex
    audience: ["web", "mobile"]
    signing_method: HS256
  
  password:
    min_length: 8
    hash_algorithm: argon2id
    hash_memory: 65536
    hash_iterations: 3

  session:
    enabled: true
    store: redis
    cookie_name: session
    cookie_path: /
    max_age: 24h
    secure: true
    http_only: true

command_bus:
  middleware:
    validation:
      enabled: true
    transaction:
      enabled: true
      propagation: required
      timeout: 5s
      isolation: read_committed
    events:
      enabled: true
      async_publishing: true
      batch_size: 100
      retry_attempts: 3

  handlers:
    timeout: 10s
    max_concurrency: 100
    retry_attempts: 3
    retry_delay: 1s

  metrics:
    namespace: gohex_commands
    collect_interval: 10s
    export_path: /metrics

query_bus:
  middleware:
    validation:
      enabled: true
    cache:
      enabled: true
      ttl: 5m
    retry:
      enabled: true
      max_retries: 3
      backoff: 100ms
    timeout:
      enabled: true
      default: 5s 